### ISSUE TITLE
Fix the image on the wordpress plugin repo

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/billmate-order-mangement-for-woocommerce#18]
![Skärmavbild 2021-01-27 kl  08 07 51](https://user-images.githubusercontent.com/4968755/105955554-c3a96c80-6076-11eb-862c-76788786ff23.png)

**Comment by MattiasNilsson** [comment]
It is now fixed and taken care of: https://wordpress.org/plugins/billmate-order-management-for-woocommerce/
