### ISSUE TITLE
Support to handle orders from previous plugin

### ISSUE THREAD

**Issue by billmate-support** [Billmate/billmate-order-mangement-for-woocommerce#20]
When migrating from the previous plugin to the new plugin the orders created by the previous plugin are not being handled by the order management module. 

<p></p>

We are thinking about adding support to activate/refund/cancel orders that is created with the previous plugin, Billmate Payment Gateway for WooCommerce.  

<p></p>

## Proposed solution

Support for prevous olugins transactions. Automaticlly activate.

Warning if old plugin is enabled and order management is enabled as well.  
wordpres_notice

**Comment by billmate-support** [comment]
Link to feature: https://billmate.productboard.com/feature-board/planning/features/6837171

**Comment by stefanliden** [comment]
Tested the functionality and it works well 👍

**Comment by andyjohansson** [comment]
Let's add the transaltions as well to the pull request.

**Comment by NiklasHogefjord** [comment]
Translation added. New version released. Closing this issue.
