### ISSUE TITLE
updatePayment customer shipping, billing address expect country code

### ISSUE THREAD

**Issue by kalorifri** [Billmate/billmate-order-mangement-for-woocommerce#29]
When updatePayment request, Billmate API expect country in customer billing and shipping address to be formatted as ISO 3166-1 2-character country code in uppercase (e.g. Sweden: "SE").

gz#179401

**Comment by NiklasHogefjord** [comment]
Hi @kalorifri, sorry for the very late reply.

According to Billmate's docs (https://billmate.github.io/api-docs/#updatepayment) this is not correct. The correct structure is to name it as "Sweden". This is how we do it in the plugin now.

**Comment by NiklasHogefjord** [comment]
Hi again @kalorifri,
After discussions with Billmate it seems as the documentation isn't correct. I will look into it in the plugin and release a new version next week.

**Comment by NiklasHogefjord** [comment]
Fixed and updated now (the updated code is actually located in Billmate Checkout for WooCommerce).
